apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pgage
spec:
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: age
    major: 16

  instances: 1

  bootstrap:
    initdb:
      postInitTemplateSQL:
        - CREATE EXTENSION vector;
        - CREATE EXTENSION age;
        - GRANT SELECT ON ag_catalog.ag_graph TO app;
        - GRANT USAGE ON SCHEMA ag_catalog TO app;

  storage:
    size: 2Gi